console.log(1==1);
console.log(1===1);
console.log(1=='1');
console.log(1==='1')
console.log('------------')
console.log(1==true)
console.log(2==true)
console.log(1===true)
console.log(2===true)
console.log(-1==true)
console.log(-1===true)
console.log('------------')
console.log('1'===true)
console.log('2'===true)
console.log('1'==true)
console.log('2'==true)